require File.dirname(__FILE__) + '/peegee/table'
require File.dirname(__FILE__) + '/peegee/constraint'
require File.dirname(__FILE__) + '/peegee/unique_constraint'
require File.dirname(__FILE__) + '/peegee/primary_key'
require File.dirname(__FILE__) + '/peegee/foreign_key'
require File.dirname(__FILE__) + '/peegee/index'
require File.dirname(__FILE__) + '/peegee/configuration'
require File.dirname(__FILE__) + '/peegee/table_does_not_exist_error'
